version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "ci(py-deps)"
  - package-ecosystem: github-actions
    directory: ".github/workflows"
    schedule:
      interval: "daily"
    target-branch: "main"
    commit-message:
      prefix: "ci(workflow-deps)"
