name: Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  
  Run-Tests:

    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:

      - name: Checkout pytket-mbqc
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'

      - name: Install pytket-mbqc
        run: pip install pytket-mbqc-py/

      - name: Type Check
        run: mypy pytket-mbqc-py/pytket_mbqc_py/ --warn-unused-ignores

      - name: Lint Check
        run: ruff check

      - name: Format Check
        run: ruff format --check

      - name: Run Tests
        run: pytest --cov-report --cov-fail-under=100 term-missing:skip-covered --cov=pytket-mbqc-py/pytket_mbqc_py/ pytket-mbqc-py/tests/ --durations=10


  Build-Documentation:

    runs-on: ubuntu-latest
    steps:

      - name: Checkout pytket-mbqc
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install pytket-benchmarking
        run: pip install pytket-mbqc-py/

      - name: Check Documentation coverage
        run: docstr-coverage pytket-mbqc-py/pytket_mbqc_py

      - name: Build documentation
        run: |
          cd pytket-mbqc-py
          make html

      - name: Save documentation
        uses: actions/upload-artifact@v4
        with:
          name: docs_html
          path: pytket-mbqc-py/build/html
